quarkus.http.port=8080

interest_rate = 15
ceo="anand kumar patel"
branch_list=jaipur,jodhpur,bikaner,nagaur

jaipur_interest_rate=13
jodhpur_interest_rate=14
bikaner_interest_rate=15
nagaur_interest_rate=16

anand.banking.bank_name=Anand Banking
anand.banking.head_office=Mumbai
anand.banking.stock_listing=NSE,BSE